<?php

namespace BurgerBundle\Repository;

/**
 * CruditeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CruditeRepository extends \Doctrine\ORM\EntityRepository
{
}
