<?php

namespace BurgerBundle\Repository;

/**
 * SupplementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplementRepository extends \Doctrine\ORM\EntityRepository
{
}
