<?php

namespace BurgerBundle\Repository;

/**
 * TypeFriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeFriteRepository extends \Doctrine\ORM\EntityRepository
{
}
