<?php

namespace BurgerBundle\Repository;

/**
 * TypeProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
