
user_custom:
    resource: "@UserCustomBundle/Controller/"
    type:     annotation

burger:
    resource: "@BurgerBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /administration

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /administration
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
user_custom:
    resource: "@UserCustomBundle/Controller/"
    type:     annotation

login_failure:
    path: /log_fail 
    defaults:  { _controller: UserCustomBundle:Security:login } 
    
    
burger_moncompte:
    path: /moncompte 
    defaults:  { _controller: BurgerBundle:Default:moncompte }    
    
